USE LOCADORA_AUTOMOVEIS;

--  Número de vezes que um carro foi alugado
SELECT PLACA, COUNT(ID) AS "N DE ALUGUEIS" 
FROM CONTRATO
GROUP BY PLACA
ORDER BY COUNT(ID);

-- Número de vezes que um cliente alugou um carro
SELECT  NOME,  COUNT(PLACA) AS "N de Alugueis", contrato.CPF
FROM CONTRATO, cliente
WHERE contrato.CPF = cliente.CPF
GROUP BY contrato.CPF;

-- Lista de clientes que alugaram todos os carros
SELECT NOME, CPF
FROM CLIENTE
WHERE NOT EXISTS (
    SELECT 1
    FROM VEICULO
    WHERE PLACA NOT IN (
        SELECT PLACA 
        FROM CONTRATO 
        WHERE CLIENTE.CPF = CONTRATO.CPF
    )
);

SELECT ANO AS "Ano com mais contratos"
FROM CONTRATOS_POR_ANO
WHERE QTD IN (
	SELECT MAX(QTD)
	FROM CONTRATOS_POR_ANO
);

-- Obter todos os veículos de um determinado modelo e marca especificos
SELECT * 
FROM VEICULO 
JOIN MODELO ON VEICULO.MODELO_ID = MODELO.ID
WHERE (MARCA = 'CHEVROLET') AND (MODELO = 'VOLT'); 

-- σ (MARCA = ‘FORD’ AND MODELO = ‘ECOSPORT’) (VEICULO_POR_MODELO) 

SELECT CLIENTE.CPF, ID, VALOR 
FROM CONTRATOS_SELECIONADOS 
JOIN CLIENTE ON CONTRATOS_SELECIONADOS.CPF = CLIENTE.CPF; 

-- Consultar o custo médio de manutenção de veículos de uma determinada marca. 
SELECT MARCA, AVG(VALOR) AS MEDIA_VALOR_MANUTENCAO
FROM MODELO
JOIN MANUTENCAO ON MODELO.ID = MANUTENCAO.MODELO_ID
WHERE MARCA = 'CHEVROLET'
GROUP BY MARCA;

