USE LOCADORA_AUTOMOVEIS;

-- PROCEDURES

-- Mudar o delimitador temporariamente
DELIMITER //

CREATE PROCEDURE GET_HISTORICO_MANUTENCAO_BY_PLACA (IN p_placa VARCHAR(7))
BEGIN
    SELECT M.DATA_MANUTENCAO, M.VALOR, M.DESCRICAO
    FROM VEICULO V
    JOIN MANUTENCAO M ON V.MODELO_ID = M.MODELO_ID
    WHERE V.PLACA = p_placa;
END //
-- Restaurar o delimitador padrão
DELIMITER ;

-- Procedure para consultar o custo médio de manutenção de uma marca específica
DELIMITER //

CREATE PROCEDURE GET_CUSTO_MEDIO_MANUTENCAO_BY_MARCA (IN p_marca VARCHAR(100))
BEGIN
    SELECT MD.MARCA, AVG(M.VALOR) AS CUSTO_MEDIO
    FROM MODELO MD
    JOIN MANUTENCAO M ON MD.ID = M.MODELO_ID
    WHERE MD.MARCA = p_marca
    GROUP BY MD.MARCA;
END //
-- Restaurar o delimitador padrão
DELIMITER ;

CALL GET_HISTORICO_MANUTENCAO_BY_PLACA('AAS463');
CALL GET_CUSTO_MEDIO_MANUTENCAO_BY_MARCA('CHEVROLET');