USE LOCADORA_AUTOMOVEIS;

-- Criação das tabelas temporarias

-- Consultar os clientes que realizaram contratos com valor de seguro acima de um certo valor. 
CREATE TEMPORARY TABLE CONTRATOS_SELECIONADOS AS 
SELECT * 
FROM CONTRATO 
WHERE VALOR_SEG > 4000.00;

-- Consultar o histórico de manutenções de um veículo baseado em sua placa. 
CREATE TEMPORARY TABLE VEICULO_SELECIONADO AS 
SELECT * 
FROM VEICULO 
WHERE PLACA= 'AAS463';

-- Pesquisas nas tabelas temporárias

SELECT CLIENTE.CPF, ID, VALOR_SEG 
FROM CONTRATOS_SELECIONADOS 
JOIN CLIENTE ON CONTRATOS_SELECIONADOS.CPF = CLIENTE.CPF;

SELECT PLACA, MANUTENCAO_ID, CUSTO_MEDIO, DATA_MANUTENCAO 
FROM VEICULO_SELECIONADO 
JOIN HISTORICO_MANUTENCAO ON VEICULO_SELECIONADO.MODELO_ID = HISTORICO_MANUTENCAO.MODELO_ID;

-- Exclusão das tabelas temporárias

DROP TABLE CONTRATOS_SELECIONADOS;
DROP TABLE VEICULO_SELECIONADO;
