USE LOCADORA_AUTOMOVEIS;

DELIMITER //

CREATE TRIGGER CALCULAR_VALOR_FINAL 
BEFORE INSERT ON CONTRATO
FOR EACH ROW
BEGIN
    SET NEW.VALOR = NEW.DIARIA * DATEDIFF(NEW.DATA_LIMITE, NEW.DATA_INICIAL) + NEW.VALOR_SEG;
END//

DELIMITER ;

drop trigger CALCULAR_VALOR_FINAL;