USE LOCADORA_AUTOMOVEIS;

CREATE VIEW CONTRATOS_POR_ANO AS
	SELECT YEAR(DATA_INICIAL) AS ANO, COUNT(ID) AS QTD
    FROM CONTRATO
    GROUP BY ANO
    ORDER BY ANO;
    
SELECT *
FROM CONTRATOS_POR_ANO;