USE LOCADORA_AUTOMOVEIS;

-- Criação das Views

-- Número de contratos feitos por ano
CREATE VIEW CONTRATOS_POR_ANO AS
	SELECT YEAR(DATA_INICIAL) AS ANO, COUNT(ID) AS QTD
    FROM CONTRATO
    GROUP BY ANO
    ORDER BY ANO;

SELECT *
FROM CONTRATOS_POR_ANO;

-- historico completo de manutenções de todos os veiculos
CREATE VIEW HISTORICO_COMPLETO_VEICULO AS
SELECT V.PLACA, M.DATA_MANUTENCAO, M.VALOR, M.DESCRICAO, MD.MODELO, MD.MARCA
FROM VEICULO V
JOIN MANUTENCAO M ON V.MODELO_ID = M.MODELO_ID
JOIN MODELO MD ON M.MODELO_ID = MD.ID;

SELECT * FROM HISTORICO_COMPLETO_VEICULO;

-- listar contratos de veiculos por cliente
CREATE VIEW CONTRATOS_POR_CLIENTE AS
SELECT C.NOME, CT.PLACA, CT.VALOR, CT.DATA_INICIAL, CT.DATA_LIMITE
FROM CLIENTE C
JOIN CONTRATO CT ON C.CPF = CT.CPF;

select * FROM CONTRATOS_POR_CLIENTE;

--  calcular o custo médio de manutenção por modelo de veículo
CREATE VIEW CUSTO_MEDIO_MANUTENCAO_POR_MODELO AS
SELECT MD.MARCA, MD.MODELO, AVG(M.VALOR) AS CUSTO_MEDIO
FROM MODELO MD
JOIN MANUTENCAO M ON MD.ID = M.MODELO_ID
GROUP BY MD.MODELO, MD.MARCA;

SELECT * FROM CUSTO_MEDIO_MANUTENCAO_POR_MODELO;

-- Deletar as Views 

DROP VIEW CONTRATOS_POR_ANO;
DROP VIEW CONTRATOS_POR_CLIENTE;
DROP VIEW HISTORICO_COMPLETO_VEICULO;