insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (33, '2010-12-15', 333.24, 'Benign neoplasm of other specified sites of urinary organs');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (37, '2019-02-23', 339.56, 'Multiple endocrine neoplasia [MEN] type I');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2019-10-14', 466.04, 'Late metabolic acidosis of newborn');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (97, '2017-07-23', 550.74, 'Secondary pigmentary degeneration');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (32, '2017-08-15', 740.55, 'Tuberculosis of hip, bacteriological or histological examination unknown (at present)');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (20, '2017-12-14', 924.96, 'Maternal distress complicating labor and delivery, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (72, '2014-04-22', 766.97, 'Injury to inferior vena cava, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (41, '2016-11-14', 561.81, 'Other and unspecified malignant neoplasms of lymphoid and histiocytic tissue, intra-abdominal lymph nodes');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (57, '2020-12-16', 639.04, 'Engorgement of breasts associated with childbirth, antepartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (50, '2014-11-29', 513.95, 'Poisoning by rabies vaccine');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (51, '2015-06-19', 878.69, 'Twin pregnancy, delivered, with or without mention of antepartum condition');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (77, '2012-02-10', 75.01, 'Other motor vehicle traffic accident involving collision on the highway injuring rider of animal; occupant of animal-drawn vehicle');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (3, '2021-06-27', 707.58, 'Cerebellar or brain stem contusion without mention of open intracranial wound, with prolonged [more than 24 hours] loss of consciousness without return to pre-existing conscious level');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (98, '2017-10-01', 129.01, 'Radiological examination, not elsewhere classified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (26, '2022-11-24', 615.9, 'Focal chorioretinitis, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (33, '2015-02-22', 121.68, 'Endometriosis of ovary');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (16, '2022-08-09', 614.77, 'Secondary malignant neoplasm of breast');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (48, '2011-12-08', 496.01, 'Chronic duodenal ileus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (33, '2020-11-15', 284.36, 'Personal history of anaphylaxis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (84, '2013-01-12', 645.62, 'Personal current military deployment status');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (60, '2018-08-23', 263.82, 'Generalized anxiety disorder');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (75, '2021-12-13', 684.45, 'Other organ or tissue replaced by other means');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (67, '2018-01-12', 459.49, 'Other anomalies of spine');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (68, '2013-11-12', 983.54, 'Rheumatic chorea with heart involvement');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (29, '2016-09-20', 596.97, 'Retention of urine, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (7, '2010-01-08', 89.47, 'Arthropathy, unspecified, site unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (2, '2018-03-24', 470.56, 'Peyronie''s disease');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (85, '2022-06-30', 836.99, 'Screening examination for smallpox');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (7, '2010-03-26', 301.57, 'Carcinoma in situ of bladder');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (85, '2016-04-13', 220.03, 'Osteoarthrosis, localized, not specified whether primary or secondary, other specified sites');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (70, '2017-12-25', 671.84, 'Tuberculosis of hip, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2017-01-09', 931.04, 'Other and unspecified superficial injury of shoulder and upper arm, infected');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (7, '2020-10-23', 243.3, 'Tuberculosis of other female genital organs, bacteriological or histological examination unknown (at present)');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (16, '2012-09-30', 410.48, 'Poisoning by benzodiazepine-based tranquilizers');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (96, '2019-12-08', 134.8, 'Malaria in the mother, delivered, with mention of postpartum complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (10, '2017-07-09', 230.29, 'Other myeloid leukemia, in relapse');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (72, '2011-12-21', 860.35, 'Other sickle-cell disease without crisis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (68, '2013-11-01', 678.03, 'Infections of nipple associated with childbirth, delivered, with or without mention of antepartum condition');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (83, '2014-11-26', 805.56, 'Quadruplet pregnancy with fetal loss and retention of one or more fetus(es), antepartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (4, '2015-10-04', 915.45, 'Open anterior dislocation of elbow');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (99, '2015-02-26', 834.43, 'Tuberculous peritonitis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (38, '2019-02-14', 199.65, 'Unspecified fall');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (76, '2014-06-01', 780.86, 'Extradural hemorrhage following injury with open intracranial wound, with brief [less than one hour] loss of consciousness');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (59, '2018-04-09', 318.85, 'Open wound of shoulder region, without mention of complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (97, '2014-03-04', 719.51, 'Cervical shortening, antepartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (54, '2015-05-21', 497.24, 'Multiple epiphyseal dysplasia');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (76, '2016-01-20', 162.42, 'Other symptoms referable to joint, multiple sites');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (29, '2020-08-02', 460.73, 'Accidental poisoning by lead and its compounds and fumes');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (47, '2010-10-14', 937.61, 'Rheumatic myocarditis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (53, '2017-10-15', 763.67, 'Rheumatic pneumonia');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (51, '2011-07-06', 779.78, 'Antivaricose drugs, including sclerosing agents, causing adverse effects in therapeutic use');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (52, '2015-04-21', 816.15, 'Sulfonamides causing adverse effects in therapeutic use');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (43, '2016-02-19', 858.15, 'Chloral hydrate group causing adverse effects in therapeutic use');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (24, '2014-08-08', 974.73, 'Toxic effect of cadmium and its compounds');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (77, '2020-07-24', 878.78, 'Drug dependence of mother, delivered, with mention of postpartum complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (19, '2012-09-08', 271.17, 'Cannabis abuse, continuous');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (85, '2014-06-12', 635.22, 'Crushing injury of face and scalp');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (94, '2011-04-07', 288.94, 'Cortex (cerebral) contusion with open intracranial wound, unspecified state of consciousness');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (84, '2018-05-21', 709.71, 'Insufficient anterior guidance');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (44, '2013-05-09', 983.49, 'Other motor vehicle traffic accident involving collision with motor vehicle injuring occupant of streetcar');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (74, '2017-09-27', 377.27, 'Vivax malaria [benign tertian]');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (4, '2016-06-01', 684.87, 'Screening for sickle-cell disease or trait');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (49, '2011-01-20', 372.94, 'Papilledema, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2013-12-28', 373.3, 'Activities involving non-running track and field events');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (39, '2011-11-02', 201.62, 'Screening mammogram for high-risk patient');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (48, '2013-06-28', 173.13, 'Acute laryngopharyngitis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (41, '2019-12-18', 826.05, 'Legally induced abortion, complicated by embolism, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (13, '2017-08-07', 588.93, 'Intestinal disaccharidase deficiencies and disaccharide malabsorption');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (66, '2010-11-04', 615.34, 'Closed fractures involving skull or face with other bones, with intracranial injury of other and unspecified nature, with brief [less than one hour] loss of consciousness');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (69, '2015-01-22', 401.36, 'Effusion of joint, lower leg');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (97, '2013-08-10', 183.09, 'Bipolar I disorder, most recent episode (or current) depressed, severe, without mention of psychotic behavior');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (37, '2014-05-28', 226.92, 'Accidental mechanical suffocation in bed or cradle');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (12, '2018-10-29', 973.49, 'Prickly heat');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (80, '2012-10-10', 405.9, 'Nephritis and nephropathy, not specified as acute or chronic, with lesion of membranous glomerulonephritis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (54, '2021-09-02', 488.26, 'Abrasion or friction burn of other, multiple, and unspecified sites, infected');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (26, '2015-03-01', 930.05, 'Other congenital anomalies of anterior segment');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (73, '2012-05-13', 496.69, 'Injury due to other war operations but occurring after cessation of hostilities');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (13, '2013-09-08', 545.58, 'Other nonthrombocytopenic purpuras');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (89, '2021-03-06', 939.58, 'Balanitis xerotica obliterans');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (92, '2017-12-18', 684.33, 'Partial androgen insensitivity');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (70, '2015-09-03', 218.38, 'Extradural hemorrhage following injury without mention of open intracranial wound, with concussion, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (72, '2010-06-30', 193.53, 'Malignant neoplasm of intestinal tract, part unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (22, '2018-06-22', 986.07, 'Accidental poisoning by lead and its compounds and fumes');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (43, '2015-10-18', 826.91, 'Injury to bladder and urethra, with open wound into cavity');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (3, '2011-04-15', 738.19, 'Unspecified disorder of lactation, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (99, '2020-10-16', 918.94, 'Full-thickness skin loss [third degree, not otherwise specified] of shoulder');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (7, '2019-11-23', 969.67, 'Intraventricular hemorrhage, grade II');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (59, '2022-02-03', 782.02, 'Poisoning by unspecified central nervous system stimulant');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (7, '2020-06-16', 897.13, 'Major anomalies of jaw size, macrogenia');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (13, '2020-09-10', 594.08, 'Vesical fistula, not elsewhere classified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (11, '2014-04-19', 968.89, 'Malignant neoplasm of esophagus, unspecified site');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (70, '2013-11-20', 889.01, 'Injury to deep plantar blood vessels');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (60, '2018-06-19', 461.13, 'Congenital pes planus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (60, '2020-09-18', 922.84, 'Talipes valgus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (50, '2011-04-01', 314.81, 'Hepatitis, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (38, '2021-01-16', 582.6, 'Post traumatic seizures');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (85, '2013-03-31', 642.51, 'Diabetes with renal manifestations, type II or unspecified type, not stated as uncontrolled');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (42, '2011-02-03', 549.37, 'Open wound of pharynx, without mention of complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (98, '2013-09-22', 390.82, 'Tuberculosis of peripheral lymph nodes, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (60, '2015-12-18', 809.93, 'Other specified procreative management');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2018-01-08', 753.63, 'Tuberculous abscess of brain, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (1, '2016-02-16', 791.57, 'Osteoporosis, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (18, '2018-02-25', 597.45, 'Acute nonsuppurative otitis media, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (31, '2020-05-30', 178.22, 'Poisoning by other and unspecified drugs acting on muscles');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (86, '2015-07-31', 812.46, 'Mitral valve stenosis and aortic valve insufficiency');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (27, '2010-11-13', 342.12, 'Other specified tuberculosis of central nervous system, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (55, '2018-10-24', 73.4, 'Other specified pervasive developmental disorders, current or active state');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (87, '2022-02-10', 196.92, 'Paralytic ileus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (91, '2012-06-12', 339.96, 'Foreign body in main bronchus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (84, '2018-12-07', 51.72, 'Autoimmune hemolytic anemias');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (23, '2017-05-17', 730.4, 'Incisional ventral hernia, with gangrene');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (50, '2021-12-01', 339.69, 'Closed fractures involving skull or face with other bones, without mention of intracranial injury, with brief [less than one hour] loss of consciousness');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (72, '2021-06-16', 514.97, 'Failed attempted abortion complicated by renal failure');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (77, '2013-03-21', 216.7, 'Family history of infectious and parasitic diseases');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (5, '2011-05-30', 348.22, 'Subjective visual disturbance, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (33, '2012-12-08', 938.85, 'Isoimmunization from other and unspecified blood-group incompatibility, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (83, '2011-05-04', 544.39, 'Accidental poisoning by unspecified tranquilizer');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (57, '2020-10-28', 450.62, 'Multiple endocrine neoplasia [MEN] type I');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (44, '2011-08-16', 716.3, 'Intervertebral disc disorder with myelopathy, thoracic region');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (47, '2019-12-03', 768.01, 'Macrodactylia of toes');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (39, '2010-02-13', 205.2, 'Effusion of joint, forearm');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (99, '2013-05-22', 481.36, 'Procedure not carried out for other reasons');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (81, '2015-12-08', 696.72, 'Contact with and (suspected) exposure to aromatic amines');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (5, '2022-12-27', 463.92, 'Other cardiorespiratory problems');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (27, '2014-07-14', 400.59, 'Malignant neoplasm of liver, secondary');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (50, '2011-01-01', 607.54, 'Poisoning by anti-infectives and other drugs and preparations for ear, nose, and throat');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (44, '2014-03-22', 576.64, 'Other iris atrophy');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (7, '2013-04-24', 377.28, 'Other venous embolism and thrombosis of inferior vena cava');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (50, '2016-01-01', 480.67, 'Malignant neoplasm of isthmus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (49, '2010-04-04', 81.77, 'Hallucinogen abuse, in remission');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (4, '2010-02-18', 777.76, 'Third-degree perineal laceration, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (2, '2016-09-13', 413.17, 'Tuberculous abscess of spinal cord, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (37, '2022-11-29', 228.95, 'Erythema [first degree] of toe(s) (nail)');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (38, '2017-10-05', 820.64, 'Other fluid overload');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (63, '2017-07-21', 605.67, 'Closed fracture of base of skull with intracranial injury of other and unspecified nature, with loss of consciousness of unspecified duration');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (52, '2017-04-05', 691.56, 'Other motor vehicle nontraffic accident while boarding and alighting injuring rider of animal; occupant of animal-drawn vehicle');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (55, '2018-06-13', 84.89, 'Other problems with head, neck, and trunk');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (95, '2020-11-20', 886.5, 'Accident caused by handgun');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (69, '2011-11-20', 749.39, 'Syphilis of lung');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (44, '2014-07-10', 376.87, 'Cerebellar or brain stem contusion with open intracranial wound, with moderate [1-24 hours] loss of consciousness');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (97, '2011-01-26', 978.59, 'Schizoaffective disorder, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (83, '2017-04-30', 293.08, 'Open wound of buccal mucosa, complicated');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (18, '2016-08-10', 734.05, 'Presenile dementia with depressive features');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (95, '2011-09-05', 491.78, 'Tuberculous pleurisy in primary progressive tuberculosis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (26, '2021-11-24', 664.44, 'Motor vehicle traffic accident involving collision with other vehicle injuring unspecified person');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (52, '2012-03-08', 549.58, 'Closed fracture of base of skull with cerebral laceration and contusion, with no loss of consciousness');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (84, '2019-11-16', 986.39, 'Poisoning by agricultural and horticultural chemical and pharmaceutical preparations other than plant foods and fertilizers, undetermined whether accidentally or purposely inflicted');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (86, '2012-07-12', 486.81, 'Familial polycythemia');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (77, '2020-08-15', 264.38, 'Epidemic vertigo');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (12, '2012-04-04', 540.82, 'Other acute otitis externa');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (57, '2021-05-12', 823.38, 'Unspecified secondary syphilis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (49, '2020-06-25', 934.07, 'Contusion of unspecified part of upper limb');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (49, '2021-01-08', 204.17, 'Burn of unspecified degree of thumb (nail)');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (93, '2017-05-23', 340.56, 'Neurofibromatosis, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (44, '2018-04-08', 591.04, 'Cracked nipple associated with childbirth, delivered, with or without mention of antepartum condition');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (26, '2018-01-11', 451.48, 'Unspecified noninflammatory disorder of vulva and perineum');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (82, '2021-10-29', 807.89, 'Need for prophylactic vaccination and inoculation against smallpox');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (89, '2012-09-13', 802.35, 'Malignant neoplasm of ill-defined sites within the lip and oral cavity');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (34, '2015-06-30', 844.12, 'Frostbite of face');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (55, '2017-01-29', 193.77, 'Exstrophy of urinary bladder');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (64, '2014-11-11', 999.94, 'Poisoning by unspecified drug or medicinal substance');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (8, '2011-11-21', 582.25, 'Keratitis or keratoconjunctivitis in exanthema');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (59, '2020-01-26', 764.92, 'Fetal malnutrition without mention of "light-for-dates", 2,000-2,499 grams');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (42, '2011-12-24', 823.06, 'Actinomycotic infection of other specified sites');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2010-11-22', 635.06, 'Mild stage glaucoma');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (2, '2010-12-30', 58.04, 'Injury due to war operations by aerial bomb');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (29, '2019-05-04', 258.94, 'Angiodysplasia of stomach and duodenum without mention of hemorrhage');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (93, '2020-09-07', 477.29, 'Catatonic type schizophrenia, subchronic');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (52, '2015-08-15', 87.85, 'Developmental reading disorder, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (95, '2011-06-09', 312.37, 'Thalassemia, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (96, '2015-10-21', 611.81, 'Activities involving rowing, canoeing, kayaking, rafting and tubing');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (71, '2011-06-05', 172.49, 'Unspecified abortion, complicated by embolism, complete');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (3, '2015-06-29', 680.15, 'Hemolytic disease of fetus or newborn due to ABO isoimmunization');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (31, '2015-07-22', 954.33, 'Spectator at an event');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (46, '2019-08-06', 82.5, 'Foreign body in respiratory tree, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (63, '2013-08-21', 479.5, 'Chondrocalcinosis, due to pyrophosphate crystals, ankle and foot');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (19, '2018-05-28', 818.88, 'Personal history of traumatic brain injury');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (53, '2014-07-07', 957.66, 'Multiple endocrine neoplasia [MEN] type IIB');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (21, '2010-09-15', 183.38, 'Pneumonitis due to toxoplasmosis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (66, '2012-07-04', 736.78, 'Organ or tissue replaced by other means, heart assist device');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (51, '2020-06-15', 637.27, 'Stromal corneal pigmentations');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (62, '2021-11-09', 959.02, 'Gonococcal epididymo-orchitis, chronic');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (74, '2018-07-17', 640.0, 'Vulvar and perineal hematoma, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (38, '2012-09-16', 545.6, 'External thrombosed hemorrhoids');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (79, '2021-04-27', 617.13, 'Other dysphagia');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (80, '2011-02-03', 593.22, 'Arthropathy, unspecified, multiple sites');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (85, '2019-04-05', 177.17, 'Unspecified vitamin B deficiency');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (30, '2010-04-19', 199.0, 'High vaginal laceration, postpartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (5, '2019-09-22', 788.34, 'Triplet pregnancy with fetal loss and retention of one or more fetus(es), antepartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (50, '2011-03-12', 770.61, 'Unspecified general medical examination');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (95, '2018-02-20', 547.28, 'Poisoning by parathyroid and parathyroid derivatives');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (13, '2012-12-25', 210.34, 'Body Mass Index 31.0-31.9, adult');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (70, '2021-09-08', 556.74, 'Sciatica');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (15, '2014-09-20', 152.91, 'Congenital musculoskeletal deformities of sternocleidomastoid muscle');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (37, '2020-03-11', 548.84, 'Echinococcus granulosus infection of thyroid');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (88, '2014-01-10', 745.74, 'Personal history of allergy to unspecified medicinal agent');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (42, '2016-05-17', 176.04, 'Acute gastric ulcer with hemorrhage and perforation, with obstruction');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (69, '2010-10-20', 935.56, 'Progressive bulbar palsy');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (2, '2015-12-22', 837.57, 'Personal history of anaphylaxis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (19, '2017-11-26', 569.85, 'Foreign body in anus and rectum');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (51, '2022-05-03', 716.3, 'Disseminated candidiasis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (25, '2010-12-21', 744.78, 'Syphilitic ruptured cerebral aneurysm');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (62, '2011-09-08', 995.78, 'Shoulder (girdle) dystocia, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (58, '2011-02-20', 173.85, 'Other ulcerative colitis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2013-10-27', 235.47, 'Other specified disorders of bladder');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (31, '2016-06-14', 252.9, 'Perforation of esophagus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (20, '2017-01-19', 219.02, 'Cor triatriatum');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (9, '2011-07-02', 719.86, 'Primary central nervous system lymphoma, unspecified site, extranodal and solid organ sites');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (67, '2014-04-23', 776.76, 'Secondary neuroendocrine tumor of bone');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (19, '2021-01-25', 82.24, 'Contusion of thigh');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (69, '2014-03-19', 154.82, 'Other accidental submersion or drowning in water transport accident injuring occupant of other watercraft -- crew');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2015-09-23', 113.01, 'Poisoning by unspecified agent affecting blood constituents');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (66, '2016-05-15', 558.29, 'Congenital macular changes');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (96, '2013-09-10', 285.94, 'Myotonic chondrodystrophy');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (77, '2020-11-27', 496.73, 'Pasteurellosis');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (23, '2015-10-01', 101.93, 'Periostitis, without mention of osteomyelitis, lower leg');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (24, '2016-08-14', 976.79, 'Fever, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (56, '2015-03-23', 905.73, 'Foreign body, magnetic, in posterior wall');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (60, '2017-03-19', 567.61, 'Other complications of anesthesia or other sedation in labor and delivery, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (79, '2018-10-11', 729.81, 'Tuberculosis of mastoid, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (32, '2010-02-20', 793.01, 'Polyhydramnios, antepartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (61, '2021-10-26', 398.43, 'Traumatic amputation of arm and hand (complete) (partial), bilateral [any level], without mention of complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (60, '2017-06-14', 213.32, 'Tuberculous fibrosis of lung, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (94, '2012-04-25', 807.17, 'Fetal-maternal hemorrhage, antepartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (76, '2022-01-02', 98.47, 'Specified congenital anomalies of orbit');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (45, '2015-09-01', 409.68, 'Injury to multiple sites of nerve roots and spinal plexus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (7, '2018-09-16', 592.6, 'Poisoning by other and unspecified anti-infectives');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (9, '2016-06-10', 571.94, 'Unspecified disorder of calcium metabolism');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (83, '2021-01-15', 754.27, 'Dissociative disorder or reaction, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (47, '2015-12-02', 742.19, 'No other household member able to render care');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (97, '2011-12-30', 320.25, 'Kyphoscoliotic heart disease');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (82, '2018-04-06', 556.04, 'Arthus phenomenon');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (94, '2012-07-22', 982.5, 'Genetic torsion dystonia');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (71, '2022-01-14', 492.21, 'Cough variant asthma');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (98, '2021-10-12', 350.79, 'Other closed skull fracture without mention of intracranial injury, with prolonged [more than 24 hours] loss of consciousness, without return to pre-existing conscious level');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (53, '2022-01-12', 416.35, 'Other specified types of schizophrenia, chronic');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (91, '2017-09-18', 635.94, 'Other bone involvement in diseases classified elsewhere');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (17, '2011-12-07', 201.15, 'Injury to celiac and mesenteric arteries, other');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (97, '2022-04-18', 67.9, 'Peripheral T cell lymphoma, intrathoracic lymph nodes');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (84, '2018-05-05', 627.34, 'Partial retinal arterial occlusion');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (16, '2011-07-26', 573.92, 'Complications of reattached hand');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (47, '2011-10-14', 443.85, 'Closed fracture of coronoid process of ulna');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (47, '2020-08-19', 137.79, 'Unspecified renal disease in pregnancy, without mention of hypertension, delivered, with or without mention of antepartum condition');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (35, '2017-01-23', 471.99, 'Closed fracture of base of skull with other and unspecified intracranial hemorrhage, with concussion, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (15, '2016-10-31', 519.67, 'Catatonic type schizophrenia, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (63, '2012-12-14', 242.13, 'Transient disorder of initiating or maintaining sleep');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (16, '2015-05-26', 155.52, 'Other obstructive defects of renal pelvis and ureter');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (1, '2010-10-22', 511.35, 'Infection of kidney, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (44, '2020-05-02', 332.47, 'Papanicolaou smear of anus with cytologic evidence of malignancy');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (20, '2021-04-06', 928.04, 'Monocular esotropia with V pattern');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (12, '2018-09-03', 249.5, 'Disturbance of salivary secretion');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (42, '2013-09-01', 448.23, 'Family disruption due to child in welfare custody');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (14, '2010-09-04', 554.23, 'Edema or excessive weight gain in pregnancy, without mention of hypertension, delivered, with or without mention of antepartum complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (91, '2020-05-02', 810.61, 'Nodular prostate without urinary obstruction');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (71, '2014-03-07', 571.67, 'Open fracture of base of skull without mention of intracranial injury, with prolonged [more than 24 hours] loss of consciousness, without return to pre-existing conscious level');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (99, '2014-11-03', 967.6, 'Open wound of forearm, with tendon involvement');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (87, '2021-09-21', 61.96, 'Extradural hemorrhage following injury without mention of open intracranial wound, with loss of consciousness of unspecified duration');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (81, '2020-02-16', 848.86, 'Glaucoma associated with other lens disorders');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (20, '2010-04-01', 163.14, 'Open fracture of cuneiform, foot');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (73, '2014-10-21', 618.72, 'Other cells and casts in urine');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (28, '2021-03-20', 323.76, 'Mycosis fungoides, lymph nodes of multiple sites');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (24, '2013-02-22', 483.56, 'Injury due to war operations by other forms of conventional warfare');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (1, '2017-01-03', 227.94, 'Toxic effect of caustic, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (17, '2021-06-10', 572.49, 'Open fracture of vault of skull with intracranial injury of other and unspecified nature, with prolonged [more than 24 hours] loss of consciousness and return to pre-existing conscious level');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (17, '2014-11-11', 645.97, 'Infestation, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (8, '2020-10-08', 106.09, 'Aftercare following surgery for injury and trauma');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (53, '2019-03-22', 212.56, 'Open fracture of first cervical vertebra');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (58, '2022-06-27', 784.23, 'Gallstone ileus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (13, '2013-01-26', 557.93, 'Open fracture of unspecified condyle(s) of humerus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (89, '2013-12-25', 208.05, 'Contusion of face, scalp, and neck except eye(s)');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (54, '2020-03-20', 635.39, 'Malignant neoplasm of bronchus and lung, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (48, '2019-03-03', 238.97, 'Suicide and self-inflicted injury by scald');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (28, '2014-02-04', 282.45, 'Tuberculosis of ureter, bacteriological or histological examination unknown (at present)');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (6, '2013-03-20', 266.2, 'Screening examination for leprosy (Hansen''s disease)');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (15, '2016-04-12', 761.69, 'Family disruption due to child in foster care or in care of non-parental family member');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (13, '2013-10-25', 967.08, 'Elevated carcinoembryonic antigen [CEA]');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (5, '2013-09-27', 153.39, 'Talipes valgus');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (39, '2022-07-20', 479.26, 'Cephalosporin group causing adverse effects in therapeutic use');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (52, '2010-12-17', 314.1, 'Open wound of buttock, complicated');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (3, '2016-01-20', 73.67, 'Other open skull fracture with other and unspecified intracranial hemorrhage, with concussion, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (53, '2010-04-29', 123.44, 'Postoperative shock, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (22, '2022-04-28', 505.64, 'Dysfunctions associated with sleep stages or arousal from sleep');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (31, '2021-09-14', 991.98, 'Muscular wasting and disuse atrophy, not elsewhere classified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (62, '2016-09-15', 330.4, 'Ankylosis of joint, upper arm');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (35, '2016-05-20', 846.82, 'Secondary and unspecified malignant neoplasm of lymph nodes, site unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (42, '2015-11-27', 301.9, 'Other closed fracture of lower end of femur');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (35, '2018-10-20', 753.12, 'Painful respiration');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (43, '2010-08-06', 699.34, 'Injury to sacral nerve root');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (73, '2017-09-29', 461.85, 'Pneumonia due to Staphylococcus, unspecified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (60, '2020-05-27', 961.95, 'Lesion of plantar nerve');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (57, '2015-06-14', 993.93, 'Other specified indications for care or intervention related to labor and delivery, antepartum condition or complication');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (94, '2015-04-20', 833.04, 'Benign carcinoid tumor of foregut, not otherwise specified');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (3, '2021-10-26', 775.64, 'Chronic total occlusion of artery of the extremities');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (94, '2012-06-19', 521.78, 'Other threatened labor, unspecified as to episode of care or not applicable');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (15, '2019-12-02', 798.43, 'Osteoarthrosis, localized, secondary, forearm');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (88, '2022-07-02', 322.31, 'Other monocytic leukemia, in remission');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (66, '2012-03-21', 996.98, 'Deep necrosis of underlying tissues [deep third degree] with loss of a body part, of hand, unspecified site');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (78, '2022-06-05', 90.65, 'Tachypnea');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (40, '2018-07-02', 829.7, 'Pressure ulcer, stage I');
insert into MANUTENCAO (MODELO_ID, DATA_MANUTENCAO, VALOR, DESCRICAO) values (16, '2017-11-01', 248.56, 'Need for prophylactic vaccination and inoculation against plague');
