insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Mustang', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Sierra 1500', 'GMC');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', '650', 'BMW');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Continental', 'Lincoln');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'L300', 'Mitsubishi');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Swift', 'Suzuki');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Bonneville', 'Pontiac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Avanti', 'Studebaker');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Continental Mark VII', 'Lincoln');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'DBS', 'Aston Martin');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Astro', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Murciélago LP640', 'Lamborghini');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'X-Type', 'Jaguar');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Cayenne', 'Porsche');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'V70', 'Volvo');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Metro', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', '5 Series', 'BMW');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Thunderbird', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Charger', 'Dodge');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Grand Marquis', 'Mercury');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Escalade ESV', 'Cadillac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Town Car', 'Lincoln');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Ram Van 3500', 'Dodge');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Camry Solara', 'Toyota');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Aura', 'Saturn');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', '300E', 'Mercedes-Benz');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Grand Caravan', 'Dodge');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'MR2', 'Toyota');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'ES', 'Lexus');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'XR4Ti', 'Merkur');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Express', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'V40', 'Volvo');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'RX', 'Lexus');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'LeSabre', 'Buick');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Acclaim', 'Plymouth');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'VS Commodore', 'Holden');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Continental', 'Lincoln');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Ranger', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Expedition EL', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Sunfire', 'Pontiac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', '3500', 'GMC');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'GT-R', 'Nissan');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'H3', 'Hummer');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Prelude', 'Honda');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Fleetwood', 'Cadillac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Corvette', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Altima', 'Nissan');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Sportvan G30', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Cordia', 'Mitsubishi');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Grand Prix', 'Pontiac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Hombre', 'Isuzu');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', '3 Series', 'BMW');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Silverado 2500', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', '911', 'Porsche');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Express 3500', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Suburban 2500', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'C70', 'Volvo');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Aurora', 'Oldsmobile');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', '911', 'Porsche');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Volt', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'LS', 'Lexus');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Ranger', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Regal', 'Buick');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Monte Carlo', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'STS-V', 'Cadillac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Sentra', 'Nissan');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Pilot', 'Honda');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Villager', 'Mercury');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Silverado 2500', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Nitro', 'Dodge');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Z8', 'BMW');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Sienna', 'Toyota');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Econoline E350', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'TL', 'Acura');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Avalon', 'Toyota');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Corvette', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Sierra 3500', 'GMC');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Cabriolet', 'Volkswagen');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Firebird', 'Pontiac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Aerio', 'Suzuki');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Forester', 'Subaru');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Silverado 2500', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Imperial', 'Chrysler');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', '1500', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Town & Country', 'Chrysler');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'Tempo', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'MKT', 'Lincoln');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Solara', 'Toyota');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Skylark', 'Buick');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Passat', 'Volkswagen');
insert into MODELO (TIPO, MODELO, MARCA) values ('Sedan', 'D150', 'Dodge');
insert into MODELO (TIPO, MODELO, MARCA) values ('SUV', 'Econoline E150', 'Ford');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Express 3500', 'Chevrolet');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Escalade', 'Cadillac');
insert into MODELO (TIPO, MODELO, MARCA) values ('Conversível', 'Challenger', 'Dodge');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Lancer', 'Mitsubishi');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Savana 3500', 'GMC');
insert into MODELO (TIPO, MODELO, MARCA) values ('Minivan', 'Sigma', 'Mitsubishi');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Virage', 'Aston Martin');
insert into MODELO (TIPO, MODELO, MARCA) values ('Picape', 'Titan', 'Nissan');